# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/shilong/long/computer network/FTP-Application/FTPClinetUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(783, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logoutButton = QtWidgets.QPushButton(self.centralwidget)
        self.logoutButton.setGeometry(QtCore.QRect(500, 50, 89, 25))
        self.logoutButton.setObjectName("logoutButton")
        self.loginButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginButton.setGeometry(QtCore.QRect(640, 50, 89, 25))
        self.loginButton.setDefault(True)
        self.loginButton.setObjectName("loginButton")
        self.ipEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.ipEdit.setGeometry(QtCore.QRect(60, 10, 113, 25))
        self.ipEdit.setObjectName("ipEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 67, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 10, 67, 17))
        self.label_2.setObjectName("label_2")
        self.portEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.portEdit.setGeometry(QtCore.QRect(260, 10, 113, 25))
        self.portEdit.setObjectName("portEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(390, 10, 67, 17))
        self.label_3.setObjectName("label_3")
        self.usernameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.usernameEdit.setGeometry(QtCore.QRect(440, 10, 113, 25))
        self.usernameEdit.setObjectName("usernameEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(580, 10, 67, 17))
        self.label_4.setObjectName("label_4")
        self.passwordEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordEdit.setGeometry(QtCore.QRect(630, 10, 113, 25))
        self.passwordEdit.setText("")
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.msgShow = QtWidgets.QLabel(self.centralwidget)
        self.msgShow.setGeometry(QtCore.QRect(10, 530, 381, 17))
        self.msgShow.setObjectName("msgShow")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 67, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(450, 100, 67, 17))
        self.label_6.setObjectName("label_6")
        self.listLocal = QtWidgets.QListView(self.centralwidget)
        self.listLocal.setGeometry(QtCore.QRect(450, 120, 311, 401))
        self.listLocal.setObjectName("listLocal")
        self.listRemote = QtWidgets.QListView(self.centralwidget)
        self.listRemote.setGeometry(QtCore.QRect(10, 120, 311, 401))
        self.listRemote.setObjectName("listRemote")
        self.radioPASV = QtWidgets.QRadioButton(self.centralwidget)
        self.radioPASV.setGeometry(QtCore.QRect(80, 50, 61, 23))
        self.radioPASV.setObjectName("radioPASV")
        self.radioPORT = QtWidgets.QRadioButton(self.centralwidget)
        self.radioPORT.setGeometry(QtCore.QRect(10, 50, 61, 23))
        self.radioPORT.setObjectName("radioPORT")
        self.downloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.downloadButton.setGeometry(QtCore.QRect(340, 240, 89, 25))
        self.downloadButton.setObjectName("downloadButton")
        self.uploadButton = QtWidgets.QPushButton(self.centralwidget)
        self.uploadButton.setGeometry(QtCore.QRect(340, 340, 89, 25))
        self.uploadButton.setObjectName("uploadButton")
        self.remotePathLabel = QtWidgets.QLabel(self.centralwidget)
        self.remotePathLabel.setGeometry(QtCore.QRect(80, 99, 241, 21))
        self.remotePathLabel.setText("")
        self.remotePathLabel.setObjectName("remotePathLabel")
        self.localPathLabel = QtWidgets.QLabel(self.centralwidget)
        self.localPathLabel.setGeometry(QtCore.QRect(520, 99, 231, 21))
        self.localPathLabel.setText("")
        self.localPathLabel.setObjectName("localPathLabel")
        self.refreshRemote = QtWidgets.QPushButton(self.centralwidget)
        self.refreshRemote.setGeometry(QtCore.QRect(290, 490, 31, 31))
        self.refreshRemote.setObjectName("refreshRemote")
        self.refreshLocal = QtWidgets.QPushButton(self.centralwidget)
        self.refreshLocal.setGeometry(QtCore.QRect(730, 490, 31, 31))
        self.refreshLocal.setObjectName("refreshLocal")
        self.delRemoteButton = QtWidgets.QPushButton(self.centralwidget)
        self.delRemoteButton.setGeometry(QtCore.QRect(260, 490, 31, 31))
        self.delRemoteButton.setObjectName("delRemoteButton")
        self.delLocalButton = QtWidgets.QPushButton(self.centralwidget)
        self.delLocalButton.setGeometry(QtCore.QRect(700, 490, 31, 31))
        self.delLocalButton.setObjectName("delLocalButton")
        self.renameRemoteButton = QtWidgets.QPushButton(self.centralwidget)
        self.renameRemoteButton.setGeometry(QtCore.QRect(230, 490, 31, 31))
        self.renameRemoteButton.setObjectName("renameRemoteButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 783, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.logoutButton.setText(_translate("MainWindow", "注销账户"))
        self.loginButton.setText(_translate("MainWindow", "登录"))
        self.ipEdit.setText(_translate("MainWindow", "127.0.0.1"))
        self.label.setText(_translate("MainWindow", "目标ip"))
        self.label_2.setText(_translate("MainWindow", "目标端口"))
        self.portEdit.setText(_translate("MainWindow", "21"))
        self.label_3.setText(_translate("MainWindow", "用户名"))
        self.usernameEdit.setText(_translate("MainWindow", "anonymous"))
        self.label_4.setText(_translate("MainWindow", "密码"))
        self.msgShow.setText(_translate("MainWindow", "Client is ready!"))
        self.label_5.setText(_translate("MainWindow", "远程目录:"))
        self.label_6.setText(_translate("MainWindow", "本地目录:"))
        self.radioPASV.setText(_translate("MainWindow", "PASV"))
        self.radioPORT.setText(_translate("MainWindow", "PORT"))
        self.downloadButton.setText(_translate("MainWindow", "→"))
        self.uploadButton.setText(_translate("MainWindow", "←"))
        self.refreshRemote.setText(_translate("MainWindow", "の"))
        self.refreshLocal.setText(_translate("MainWindow", "の"))
        self.delRemoteButton.setText(_translate("MainWindow", "X"))
        self.delLocalButton.setText(_translate("MainWindow", "X"))
        self.renameRemoteButton.setText(_translate("MainWindow", "彡"))

